spring:
    redis:
        jedis:
            pool:
                max-active: 60
                max-wait: 5000
                min-idle: 1
                max-idle: 10
        timeout: 5000
        database: 0
        host: r-uf6b9fd7cc141fe4.redis.rds.aliyuncs.com
        port: 6379
        password: lrnJ5OPK